- hosts: tag_Name_WebServer 
  vars: 
     web_port: 80
  tasks:
          - name: Installing httpd software 
            package:
                 name: httpd
                 state: present
           
          - name: Installing PHP interpreter
            package:
                 name: php
                 state: present
       
          - name: Copying content of Web server
            copy:
                 content: '<pre>
                          <?php
                          print`/usr/sbin/ifconfig eth0`;
                          ?>
                          </pre>'
                 dest: /var/www/html/index.php
            notify:
              - Restart httpd
             
          - name: Starting httpd service
            service: 
                  name: httpd
                  state: started
  handlers:
     - name: Restart httpd
       service:
          name: httpd
          state: restarted


          
- hosts: tag_Name_Haproxy
  vars:
      - haproxy_port: 8080
      - web_port: 80

  tasks:
         - name: Installing haproxy
           package: 
                name: haproxy
                state: present
             
         - name: Configure the haproxy.cfg file
           template:
                 src: "haproxy.cfg"
                 dest: "/etc/haproxy/haproxy.cfg" 
           notify:
               - Restart haproxy
         
         - name: Starting Haproxy service
           service:
                name: haproxy
                state: started
  handlers:
     - name: Restart haproxy
       service:
          name: haproxy
          state: restarted




